# Generated by Django 4.2.1 on 2023-07-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productos",
            name="disponible",
        ),
        migrations.AddField(
            model_name="productos",
            name="precio",
            field=models.IntegerField(null=True),
        ),
    ]
